import os
import subprocess
import sys

def install_and_import(package):
    try:
        __import__("pptx")
    except ImportError:
        print(f"{package} not found. Installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package, "--user"])

install_and_import('python-pptx')

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

def create_presentation():
    prs = Presentation()
    
    # 1. Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Lock-Free SPSC Unbounded Queue"
    subtitle.text = "Deep Dive: Working, Testing, & Benchmarking\nThread-Safe Queue (tsq)\nGenerated by AI"

    # 2. Challenge Slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "The Challenge: Dropping the Locks"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Standard thread-safe queues rely heavily on std::mutex."
    p = tf.add_paragraph()
    p.text = "- Introduces massive overhead (Context switching)."
    p = tf.add_paragraph()
    p.text = "- High CPU contention when producers and consumers run simultaneously."
    p = tf.add_paragraph()
    p.text = ""
    p = tf.add_paragraph()
    p.text = "The Solution:"
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "An SPSC algorithm that passes data utilizing atomic pointers instead of locks, creating a Wait-Free & Lock-Free pipeline."

    # 3. Core Architecture
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Core Architecture: The Stub Node Pattern"
    tf = slide.shapes.placeholders[1].text_frame
    p = tf.add_paragraph()
    p.text = "Goal: Never let the consumer see a node until data inside is completely written."
    p = tf.add_paragraph()
    p.text = "1. Queue starts with 1 blank stub node. 'head' and 'tail' point to it."
    p = tf.add_paragraph()
    p.text = "2. 'tail' always points to a meaningless dummy node that the consumer ignores."
    p = tf.add_paragraph()
    p.text = "3. Producer writes data into the dummy node, creates another empty node, and assigns tail to it."

    # 4. Memory Ordering
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Synchronization: Memory Ordering"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "CPU instruction re-ordering means standard assignments cause race conditions."
    p = tf.add_paragraph()
    p.text = "Producer (Push): std::memory_order_release"
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "- Tells CPU: Do not link the pointer until memory write is fully finished."
    p = tf.add_paragraph()
    p.text = "Consumer (Pop): std::memory_order_acquire"
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "- Tells CPU: Do not read the memory until the next pointer has been verified."

    # 5. Testing
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Rigorous Validation & Testing"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Tested comprehensively in 'test_spsc_unbounded.cpp':"
    p = tf.add_paragraph()
    p.text = "[Pass] Basic Validation (Push/pop with assertions.)"
    p = tf.add_paragraph()
    p.text = "[Pass] Emplace + Peek (In-place construction and non-consuming reads.)"
    p = tf.add_paragraph()
    p.text = "[Pass] Zero/Empty Edge Cases (Prevent dangling reads.)"
    p = tf.add_paragraph()
    p.text = "[Pass] Burst & Drain (Fast pushing 10,000 items, and emptying instantly.)"
    p = tf.add_paragraph()
    p.text = "[Pass] Concurrent SPSC Stress (100,000 items checked for exact sequence.)"

    # 6. Benchmarks
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Benchmarking Throughput"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Operations processing 5,000,000 integers (ops/sec):"
    p = tf.add_paragraph()
    p.text = "Custom Blocking MPMC: 2.62 Million"
    p = tf.add_paragraph()
    p.text = "Custom Lock-Free SPSC: 4.55 Million"
    p = tf.add_paragraph()
    p.text = "Baseline std::queue: 5.57 Million"
    p = tf.add_paragraph()
    p.text = ""
    p = tf.add_paragraph()
    p.text = "Analysis:"
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "Lock-Free is ~2x faster than custom blocking. However, std::queue wins due to memory allocation chunking."

    # 7. Next Steps
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Next Phase: The Bounded Ring Buffer"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "The Unbounded Lock-Free Queue exposed 'new node()' allocations as the ultimate bottleneck."
    p = tf.add_paragraph()
    p.text = "- The final evolution is our lockfree_spsc_bounded queue."
    p = tf.add_paragraph()
    p.text = "- Moves the memory to a compile-time Ring Buffer."
    p = tf.add_paragraph()
    p.text = "- Zero runtime allocations will obliterate all existing baseline benchmarks."
    
    # Save Presentation
    pptx_path = "LockFree_Queue_Presentation.pptx"
    prs.save(pptx_path)
    print(f"Presentation generated at: {os.path.abspath(pptx_path)}")

if __name__ == "__main__":
    create_presentation()
